[2023-03-27T01:46:01.646+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_google_sheet_v01.get_sklearn scheduled__2023-03-26T00:00:00+00:00 [queued]>
[2023-03-27T01:46:01.709+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_google_sheet_v01.get_sklearn scheduled__2023-03-26T00:00:00+00:00 [queued]>
[2023-03-27T01:46:01.727+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T01:46:01.730+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-27T01:46:01.731+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T01:46:01.833+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-03-26 00:00:00+00:00
[2023-03-27T01:46:01.872+0000] {standard_task_runner.py:55} INFO - Started process 269 to run task
[2023-03-27T01:46:01.893+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_google_sheet_v01', 'get_sklearn', 'scheduled__2023-03-26T00:00:00+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/dag_rw_google_sheet.py', '--cfg-path', '/tmp/tmpqgeckedf']
[2023-03-27T01:46:01.913+0000] {standard_task_runner.py:83} INFO - Job 317: Subtask get_sklearn
[2023-03-27T01:46:02.179+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_google_sheet_v01.get_sklearn scheduled__2023-03-26T00:00:00+00:00 [running]> on host 7c9cdf1c064e
[2023-03-27T01:46:02.450+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ThinhHuynh
AIRFLOW_CTX_DAG_ID=dag_with_google_sheet_v01
AIRFLOW_CTX_TASK_ID=get_sklearn
AIRFLOW_CTX_EXECUTION_DATE=2023-03-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-26T00:00:00+00:00
[2023-03-27T01:46:02.454+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_rw_google_sheet.py", line 41, in insert_master
    dic = google_sheet.main()
  File "/opt/airflow/dags/google_sheet.py", line 39, in main
    'credentials.json', SCOPES)
  File "/home/airflow/.local/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 204, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'
[2023-03-27T01:46:02.493+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=dag_with_google_sheet_v01, task_id=get_sklearn, execution_date=20230326T000000, start_date=20230327T014601, end_date=20230327T014602
[2023-03-27T01:46:02.532+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 317 for task get_sklearn ([Errno 2] No such file or directory: 'credentials.json'; 269)
[2023-03-27T01:46:02.574+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-27T01:46:02.626+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
