[2023-03-22T15:13:24.376+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-22T08:00:25.425050+00:00 [queued]>
[2023-03-22T15:13:24.393+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-22T08:00:25.425050+00:00 [queued]>
[2023-03-22T15:13:24.394+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T15:13:24.395+0000] {taskinstance.py:1283} INFO - Starting attempt 23 of 23
[2023-03-22T15:13:24.396+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T15:13:24.423+0000] {taskinstance.py:1303} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2023-03-22 08:00:25.425050+00:00
[2023-03-22T15:13:24.429+0000] {standard_task_runner.py:55} INFO - Started process 5344 to run task
[2023-03-22T15:13:24.486+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v04', 'sensor_minio_s3', 'manual__2023-03-22T08:00:25.425050+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/minio_s3.py', '--cfg-path', '/tmp/tmpomffz5sa']
[2023-03-22T15:13:24.489+0000] {standard_task_runner.py:83} INFO - Job 204: Subtask sensor_minio_s3
[2023-03-22T15:13:25.615+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-22T08:00:25.425050+00:00 [running]> on host 9594f7270003
[2023-03-22T15:13:26.655+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ThinhHuynh
AIRFLOW_CTX_DAG_ID=dag_with_minio_s3_v04
AIRFLOW_CTX_TASK_ID=sensor_minio_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T08:00:25.425050+00:00
AIRFLOW_CTX_TRY_NUMBER=23
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T08:00:25.425050+00:00
[2023-03-22T15:13:26.664+0000] {s3.py:99} INFO - Poking for key : s3://***/data.csv
[2023-03-22T15:13:26.695+0000] {base.py:73} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2023-03-22T15:13:26.698+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from extra.
[2023-03-22T15:13:54.819+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 130, in poke
    return self._check_key(self.bucket_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 118, in _check_key
    obj = self.hook.head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 111, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 82, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 504, in head_object
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 499, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
[2023-03-22T15:13:54.833+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=dag_with_minio_s3_v04, task_id=sensor_minio_s3, execution_date=20230322T080025, start_date=20230322T151324, end_date=20230322T151354
[2023-03-22T15:13:54.859+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 204 for task sensor_minio_s3 (An error occurred (403) when calling the HeadObject operation: Forbidden; 5344)
[2023-03-22T15:13:54.911+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T15:13:54.943+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
