[2023-03-25T06:41:57.678+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_google_sheet_v01.get_sklearn manual__2023-03-25T03:59:29.617124+00:00 [queued]>
[2023-03-25T06:41:57.701+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_google_sheet_v01.get_sklearn manual__2023-03-25T03:59:29.617124+00:00 [queued]>
[2023-03-25T06:41:57.702+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T06:41:57.703+0000] {taskinstance.py:1283} INFO - Starting attempt 3 of 3
[2023-03-25T06:41:57.704+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T06:41:57.761+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-03-25 03:59:29.617124+00:00
[2023-03-25T06:41:57.780+0000] {standard_task_runner.py:55} INFO - Started process 253 to run task
[2023-03-25T06:41:57.797+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_google_sheet_v01', 'get_sklearn', 'manual__2023-03-25T03:59:29.617124+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/dag_rw_google_sheet.py', '--cfg-path', '/tmp/tmp0voghl4v']
[2023-03-25T06:41:57.817+0000] {standard_task_runner.py:83} INFO - Job 259: Subtask get_sklearn
[2023-03-25T06:41:58.016+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_google_sheet_v01.get_sklearn manual__2023-03-25T03:59:29.617124+00:00 [running]> on host 9783a48d7fca
[2023-03-25T06:41:58.190+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ThinhHuynh
AIRFLOW_CTX_DAG_ID=dag_with_google_sheet_v01
AIRFLOW_CTX_TASK_ID=get_sklearn
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T03:59:29.617124+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-25T03:59:29.617124+00:00
[2023-03-25T06:41:58.194+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_rw_google_sheet.py", line 41, in insert_master
    dic = google_sheet.main()
  File "/opt/airflow/dags/google_sheet.py", line 39, in main
    'credentials.json', SCOPES)
  File "/home/airflow/.local/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 204, in from_client_secrets_file
    with open(client_secrets_file, "r") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'
[2023-03-25T06:41:58.221+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=dag_with_google_sheet_v01, task_id=get_sklearn, execution_date=20230325T035929, start_date=20230325T064157, end_date=20230325T064158
[2023-03-25T06:41:58.254+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 259 for task get_sklearn ([Errno 2] No such file or directory: 'credentials.json'; 253)
[2023-03-25T06:41:58.297+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T06:41:58.333+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
