[2023-03-22T07:07:07.686+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-22T07:07:03.709582+00:00 [queued]>
[2023-03-22T07:07:07.718+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-22T07:07:03.709582+00:00 [queued]>
[2023-03-22T07:07:07.719+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T07:07:07.719+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-22T07:07:07.720+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T07:07:07.760+0000] {taskinstance.py:1303} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2023-03-22 07:07:03.709582+00:00
[2023-03-22T07:07:07.770+0000] {standard_task_runner.py:55} INFO - Started process 14008 to run task
[2023-03-22T07:07:07.775+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v04', 'sensor_minio_s3', 'manual__2023-03-22T07:07:03.709582+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/minio_s3.py', '--cfg-path', '/tmp/tmplzxa4g83']
[2023-03-22T07:07:07.779+0000] {standard_task_runner.py:83} INFO - Job 169: Subtask sensor_minio_s3
[2023-03-22T07:07:07.901+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-22T07:07:03.709582+00:00 [running]> on host 9594f7270003
[2023-03-22T07:07:08.111+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ThinhHuynh
AIRFLOW_CTX_DAG_ID=dag_with_minio_s3_v04
AIRFLOW_CTX_TASK_ID=sensor_minio_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T07:07:03.709582+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T07:07:03.709582+00:00
[2023-03-22T07:07:08.112+0000] {s3.py:99} INFO - Poking for key : s3://***/data.csv
[2023-03-22T07:07:08.136+0000] {base.py:73} INFO - Using connection ID 'minio_conn' for task execution.
[2023-03-22T07:07:08.139+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2023-03-22T07:07:13.552+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 130, in poke
    return self._check_key(self.bucket_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 118, in _check_key
    obj = self.hook.head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 111, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 82, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 504, in head_object
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 499, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
[2023-03-22T07:07:13.565+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_minio_s3_v04, task_id=sensor_minio_s3, execution_date=20230322T070703, start_date=20230322T070707, end_date=20230322T070713
[2023-03-22T07:07:13.588+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 169 for task sensor_minio_s3 (An error occurred (403) when calling the HeadObject operation: Forbidden; 14008)
[2023-03-22T07:07:13.638+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T07:07:13.660+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
