[2023-03-27T02:23:40.735+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_google_sheet_v01.get_data_from_google_sheet manual__2023-03-27T02:09:32.849106+00:00 [queued]>
[2023-03-27T02:23:40.818+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_google_sheet_v01.get_data_from_google_sheet manual__2023-03-27T02:09:32.849106+00:00 [queued]>
[2023-03-27T02:23:40.818+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T02:23:40.821+0000] {taskinstance.py:1283} INFO - Starting attempt 2 of 2
[2023-03-27T02:23:40.822+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T02:23:40.892+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): get_data_from_google_sheet> on 2023-03-27 02:09:32.849106+00:00
[2023-03-27T02:23:40.963+0000] {standard_task_runner.py:55} INFO - Started process 300 to run task
[2023-03-27T02:23:41.301+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_google_sheet_v01', 'get_data_from_google_sheet', 'manual__2023-03-27T02:09:32.849106+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/dag_rw_google_sheet.py', '--cfg-path', '/tmp/tmpeyy4pxzj']
[2023-03-27T02:23:41.386+0000] {standard_task_runner.py:83} INFO - Job 326: Subtask get_data_from_google_sheet
[2023-03-27T02:23:43.956+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_google_sheet_v01.get_data_from_google_sheet manual__2023-03-27T02:09:32.849106+00:00 [running]> on host 7785c43b1641
[2023-03-27T02:23:44.392+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ThinhHuynh
AIRFLOW_CTX_DAG_ID=dag_with_google_sheet_v01
AIRFLOW_CTX_TASK_ID=get_data_from_google_sheet
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T02:09:32.849106+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-27T02:09:32.849106+00:00
[2023-03-27T02:23:44.652+0000] {logging_mixin.py:137} INFO - Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=608356142737-42th0ef7f2pqknf5dqad9j6is3j7aae0.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A44629%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspreadsheets&state=9GtnHFqXqr7sutKL1jA5jRIIX3wbin&access_type=offline
[2023-03-27T02:28:12.740+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-03-27T02:28:13.003+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 300. PIDs of all processes in the group: [300]
[2023-03-27T02:28:13.012+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 300
[2023-03-27T02:28:13.085+0000] {taskinstance.py:1482} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-27T02:28:14.933+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=300, status='terminated', exitcode=0, started='02:23:40') (300) terminated with exit code 0
