[2023-03-23T02:22:47.905+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-23T02:22:45.719276+00:00 [queued]>
[2023-03-23T02:22:47.921+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-23T02:22:45.719276+00:00 [queued]>
[2023-03-23T02:22:47.922+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-23T02:22:47.923+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-23T02:22:47.923+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-23T02:22:47.950+0000] {taskinstance.py:1303} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2023-03-23 02:22:45.719276+00:00
[2023-03-23T02:22:47.956+0000] {standard_task_runner.py:55} INFO - Started process 1294 to run task
[2023-03-23T02:22:47.961+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v04', 'sensor_minio_s3', 'manual__2023-03-23T02:22:45.719276+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/minio_s3.py', '--cfg-path', '/tmp/tmp6c6v796q']
[2023-03-23T02:22:47.963+0000] {standard_task_runner.py:83} INFO - Job 226: Subtask sensor_minio_s3
[2023-03-23T02:22:48.067+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_minio_s3_v04.sensor_minio_s3 manual__2023-03-23T02:22:45.719276+00:00 [running]> on host 9783a48d7fca
[2023-03-23T02:22:48.202+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ThinhHuynh
AIRFLOW_CTX_DAG_ID=dag_with_minio_s3_v04
AIRFLOW_CTX_TASK_ID=sensor_minio_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-03-23T02:22:45.719276+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-23T02:22:45.719276+00:00
[2023-03-23T02:22:48.203+0000] {s3.py:99} INFO - Poking for key : s3://***/data.csv
[2023-03-23T02:22:48.218+0000] {base.py:73} INFO - Using connection ID 'minio_conn' for task execution.
[2023-03-23T02:22:48.220+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from login and password.
[2023-03-23T02:22:50.703+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 199, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 130, in poke
    return self._check_key(self.bucket_key)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 118, in _check_key
    obj = self.hook.head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 111, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 82, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 504, in head_object
    raise e
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 499, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
[2023-03-23T02:22:50.726+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=dag_with_minio_s3_v04, task_id=sensor_minio_s3, execution_date=20230323T022245, start_date=20230323T022247, end_date=20230323T022250
[2023-03-23T02:22:50.764+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 226 for task sensor_minio_s3 (An error occurred (403) when calling the HeadObject operation: Forbidden; 1294)
[2023-03-23T02:22:50.826+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-23T02:22:50.862+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
